version: '3.7'

services:
  api:
    build:
      context: .
      args:
        NODE_ENV: development
    command: npm run dev
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: mongo:3-xenial
    restart: always
    environment:
      MONGODB_INIT_ROOT_USERNAME: root
      MONGODB_INIT_ROOT_PASSWORD: example
    volumes:
      - data:/data/db
    ports:
      - 27017:27017

volumes:
  data:

